# Generated by Django 5.2.8 on 2025-12-03 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('anomaly_type', models.CharField(choices=[('irrigation_leak', 'Irrigation Leak'), ('heat_stress', 'Heat Stress'), ('cold_stress', 'Cold Stress'), ('dry_stress', 'Dry Stress'), ('excess_moisture', 'Excess Moisture'), ('sensor_spike', 'Sensor Spike'), ('sensor_drift', 'Sensor Drift'), ('sensor_offline', 'Sensor Offline')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('model_confidence', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('total_size_hectares', models.DecimalField(decimal_places=2, max_digits=8)),
                ('primary_crop', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AgentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('explanation_text', models.TextField()),
                ('recommended_action', models.TextField()),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('anomaly', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crop.anomalyevent')),
            ],
        ),
        migrations.CreateModel(
            name='FieldPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_variety', models.CharField(max_length=100)),
                ('area_hectares', models.DecimalField(decimal_places=2, max_digits=6)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='crop.farmprofile')),
            ],
        ),
        migrations.AddField(
            model_name='anomalyevent',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.fieldplot'),
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sensor_type', models.CharField(choices=[('soil_moisture', 'Soil Moisture'), ('air_temperature', 'Air Temperature'), ('air_humidity', 'Air Humidity')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('source', models.CharField(default='simulator', max_length=20)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='crop.fieldplot')),
            ],
            options={
                'indexes': [models.Index(fields=['plot', '-timestamp'], name='crop_sensor_plot_id_4aa742_idx')],
                'unique_together': {('plot', 'timestamp', 'sensor_type')},
            },
        ),
    ]
